apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: rancher/curl
    command: ["sleep", "3600"]
    env:
    - name: http_proxy
      value: "http://squid-proxy:3128"
    - name: https_proxy
      value: "http://squid-proxy:3128"
